import MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction
import MaleyLean.Papers.NonDegenerateConstructionAndKernelOfAdmissibility
import MaleyLean.Papers.RH.AuditRunners

#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperTargetAdequacyForcesKernelRolesStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperConstructionForcesKernelStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperKernelNonDerivabilityStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperNothingDerivableBelowKernelStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.PaperAMetricBoundaryAndNonParameterizationStatement
#print axioms MaleyLean.Papers.MinimalConditionsForAdmissibleConstruction.KernelAPlusAuditCertificate.auditSurfaceComplete_holds
#print axioms MaleyLean.Papers.RH.EndpointClosure.rhEndpoint_of_aascContext
#print axioms MaleyLean.Papers.RH.AuditRunners.rhAuditRunnerEndpointClosurePercent_eq
